# Generated by Django 3.2.7 on 2021-09-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalapp', '0002_auto_20210924_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
